Configs: Accommodate uClibc limitations
uClibc is missing quite some features of its bigger brother glibc.
In particular a legacy _IO_FILE structure, see:
https://elixir.bootlin.com/glibc/latest/C/ident/_IO_FILE

And so we saw this on attempt to builf perlbench with uClibc toolchain:
------------------------------->8-----------------------------
  827 | #   define FILE_cnt(fp) ((fp)->_IO_read_end - (fp)->_IO_read_ptr)
      |                              ^~
iperlsys.h:304:29: note: in expansion of macro 'FILE_cnt'
  304 | #define PerlSIO_get_cnt(f)  FILE_cnt(f)
      |                             ^~~~~~~~
perlio.c:3182:12: note: in expansion of macro 'PerlSIO_get_cnt'
 3182 |     return PerlSIO_get_cnt(stdio);
      |            ^~~~~~~~~~~~~~~
spec_config.h:827:51: error: 'FILE' has no member named '_IO_read_ptr'
  827 | #   define FILE_cnt(fp) ((fp)->_IO_read_end - (fp)->_IO_read_ptr)
      |                                                   ^~
iperlsys.h:304:29: note: in expansion of macro 'FILE_cnt'
  304 | #define PerlSIO_get_cnt(f)  FILE_cnt(f)
      |                             ^~~~~~~~
perlio.c:3182:12: note: in expansion of macro 'PerlSIO_get_cnt'
 3182 |     return PerlSIO_get_cnt(stdio);
      |            ^~~~~~~~~~~~~~~
------------------------------->8-----------------------------

So we make sure it is not used with help of SPEC's defines:
 * SPEC_CPU_NO_USE_STDIO_PTR
 * SPEC_CPU_NO_USE_STDIO_BASE